**DataFrame 만들기**

1) 딕셔너리

pd.DataFrame()안에는 딕셔너리를 넣어서 데이터프레임을 만들 수 있다.

딕셔너리의 key에는 열 이름이 들어가고, value에는 그 열에 해당하는 값들은 리스트의 형태로 들어가면 된다. (단, value에 해당하는 리스트의 길이가 다르면 오류가 난다.)

In [4]:
import pandas as pd
df1 = pd.DataFrame({'Color': ['blue', 'green', 'red', 'black'], \
        'Product ID': [1, 2, 3, 4], \
        'Product Name': ['t-shirt', 't-shirt', 'skirt', 'skirt']})
print(df1)

   Color  Product ID Product Name
0   blue           1      t-shirt
1  green           2      t-shirt
2    red           3        skirt
3  black           4        skirt

**2) 리스트**

pd.DataFrame() 안에는 리스트의 리스트를 넣어도 데이터프레임을 만들 수 있다.
리스트 1개가 곧 하나의 행에 해당한다. 

열 이름은 columns라는 인자로 
별도로 포함시켜야 한다. (이것도 리스트로 넣는다.) 

열 이름을 지정하지 않으면 인덱스처럼 0,1,2,3,…으로 나온다.

In [5]:
import pandas as pd
df2 = pd.DataFrame([\
    [1, 'San Diego', 100],\
    [2, 'Los Angeles', 120],\
    [3, 'San Francisco', 90],\
    [4, 'Sacramento', 115]],\
    columns = ['Store ID', 'Location', 'Number of Employees'])
print(df2)

   Store ID       Location  Number of Employees
0         1      San Diego                  100
1         2    Los Angeles                  120
2         3  San Francisco                   90
3         4     Sacramento                  115

## **[ CSV 파일 읽기 ]**

In [7]:
import pandas as pd
df = pd.read_csv('face_landmarks.csv')
print(df)

                           image_name  part_0_x  ...  part_67_x  part_67_y
0                 0805personali01.jpg        27  ...         84        134
1           1084239450_e76e00b7e7.jpg        70  ...        128        312
2                  10comm-decarlo.jpg        66  ...        116        164
3            110276240_bec305da91.jpg        42  ...        125        209
4                      1198_0_861.jpg       138  ...        265        516
..                                ...       ...  ...        ...        ...
64                    matt-mathes.jpg        85  ...        141        235
65                       person-7.jpg        32  ...         69         99
66                         person.jpg        78  ...        109        121
67  person_TjahjonoDGondhowiardjo.jpg        41  ...         77        128
68                    personalpic.jpg        40  ...         68        164

[69 rows x 137 columns]

In [8]:
df.to_csv('face_landmarks.csv')
#pandas의 dataframe을 csv 파일로 저장하려면 pd.to_csv()를 사용

In [9]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.head()
#처음부터5개 까지만 보여줌

                  image_name  part_0_x  ...  part_67_x  part_67_y
0        0805personali01.jpg        27  ...         84        134
1  1084239450_e76e00b7e7.jpg        70  ...        128        312
2         10comm-decarlo.jpg        66  ...        116        164
3   110276240_bec305da91.jpg        42  ...        125        209
4             1198_0_861.jpg       138  ...        265        516

[5 rows x 137 columns]

In [10]:
print(df)

                           image_name  part_0_x  ...  part_67_x  part_67_y
0                 0805personali01.jpg        27  ...         84        134
1           1084239450_e76e00b7e7.jpg        70  ...        128        312
2                  10comm-decarlo.jpg        66  ...        116        164
3            110276240_bec305da91.jpg        42  ...        125        209
4                      1198_0_861.jpg       138  ...        265        516
..                                ...       ...  ...        ...        ...
64                    matt-mathes.jpg        85  ...        141        235
65                       person-7.jpg        32  ...         69         99
66                         person.jpg        78  ...        109        121
67  person_TjahjonoDGondhowiardjo.jpg        41  ...         77        128
68                    personalpic.jpg        40  ...         68        164

[69 rows x 137 columns]

In [12]:
df.head(2)

                  image_name  part_0_x  ...  part_67_x  part_67_y
0        0805personali01.jpg        27  ...         84        134
1  1084239450_e76e00b7e7.jpg        70  ...        128        312

[2 rows x 137 columns]

In [16]:
df.tail()
#뒤에서 부터 데이터 보고싶다

                           image_name  part_0_x  ...  part_67_x  part_67_y
64                    matt-mathes.jpg        85  ...        141        235
65                       person-7.jpg        32  ...         69         99
66                         person.jpg        78  ...        109        121
67  person_TjahjonoDGondhowiardjo.jpg        41  ...         77        128
68                    personalpic.jpg        40  ...         68        164

[5 rows x 137 columns]

In [17]:
df.tail(3)

                           image_name  part_0_x  ...  part_67_x  part_67_y
66                         person.jpg        78  ...        109        121
67  person_TjahjonoDGondhowiardjo.jpg        41  ...         77        128
68                    personalpic.jpg        40  ...         68        164

[3 rows x 137 columns]

In [ ]:
df_image_name = df['image_name']
df_image_name
#image_name 열의 추출

0                   0805personali01.jpg
1             1084239450_e76e00b7e7.jpg
2                    10comm-decarlo.jpg
3              110276240_bec305da91.jpg
4                        1198_0_861.jpg
                    ...
64                      matt-mathes.jpg
65                         person-7.jpg
66                           person.jpg
67    person_TjahjonoDGondhowiardjo.jpg
68                      personalpic.jpg
Name: image_name, Length: 69, dtype: object

In [ ]:
df

    Unnamed: 0                         image_name  ...  part_67_x  part_67_y
0            0                0805personali01.jpg  ...         84        134
1            1          1084239450_e76e00b7e7.jpg  ...        128        312
2            2                 10comm-decarlo.jpg  ...        116        164
3            3           110276240_bec305da91.jpg  ...        125        209
4            4                     1198_0_861.jpg  ...        265        516
..         ...                                ...  ...        ...        ...
64          64                    matt-mathes.jpg  ...        141        235
65          65                       person-7.jpg  ...         69         99
66          66                         person.jpg  ...        109        121
67          67  person_TjahjonoDGondhowiardjo.jpg  ...         77        128
68          68                    personalpic.jpg  ...         68        164

[69 rows x 138 columns]

In [ ]:
df_two = df[['image_name','part_0_x']]
df_two
# 2개이상 열 추출시 리스트(list)타입으로 기술

                           image_name  part_0_x
0                 0805personali01.jpg        27
1           1084239450_e76e00b7e7.jpg        70
2                  10comm-decarlo.jpg        66
3            110276240_bec305da91.jpg        42
4                      1198_0_861.jpg       138
..                                ...       ...
64                    matt-mathes.jpg        85
65                       person-7.jpg        32
66                         person.jpg        78
67  person_TjahjonoDGondhowiardjo.jpg        41
68                    personalpic.jpg        40

[69 rows x 2 columns]

In [ ]:
df_first = df.loc[0]
df_first
#loc를 이용하여 index0과 관련된 행 추출

Unnamed: 0                      0
image_name    0805personali01.jpg
part_0_x                       27
part_0_y                       83
part_1_x                       27
                     ...
part_65_y                     135
part_66_x                      89
part_66_y                     135
part_67_x                      84
part_67_y                     134
Name: 0, Length: 138, dtype: object

In [ ]:
df_two = df.loc[[0,3]]
df_two
#리스트(list)를 통해 2개 이상의 행 추출

   Unnamed: 0                image_name  ...  part_67_x  part_67_y
0           0       0805personali01.jpg  ...         84        134
3           3  110276240_bec305da91.jpg  ...        125        209

[2 rows x 138 columns]

In [ ]:
df_part_0_y = df.groupby('image_name')
age_average = df_part_0_y['part_0_y'].mean()
print(age_average)
# image_name별로 그굽화된 데이터
# part_0_y열에 대한 평균값 계산

image_name
0805personali01.jpg                   83
1084239450_e76e00b7e7.jpg            236
10comm-decarlo.jpg                   114
110276240_bec305da91.jpg             140
1198_0_861.jpg                       392
                                    ...
matt-mathes.jpg                      152
person-7.jpg                          65
person.jpg                            83
person_TjahjonoDGondhowiardjo.jpg     92
personalpic.jpg                      109
Name: part_0_y, Length: 69, dtype: int64

## **텍스트파일 불러오기**

In [24]:
df = pd.read_csv('/content/test_text_file.txt')
df

   ID|A|B|C|D
0  C1|1|2|3|4
1  C2|5|6|7|8
2  C3|1|3|5|7

**>>Tab이 적용된 문서 가져오기**

In [43]:
#df = pd.read_csv('/content/test_tab.txt', delimiter='\t')
df = pd.read_csv('/content/test_tab.txt', sep='\t')
#df = pd.read_csv('/content/test_tab.txt')
df
#구분자가 탭(tab) 이라면 sep = '\t' 을 입력해준다.

   ID  A  B  C  D
0  C1  1  2  3  4
1  C2  5  6  7  8
2  C3  1  3  5  7

**>>head가 없는 파일 가져올때**

In [59]:
df = pd.read_csv('/content/no_title.txt')
df

   C1  1  2  3  4
0  C2  5  6  7  8
1  C3  1  3  5  7

In [60]:
df = pd.read_csv('/content/no_title.txt', header=None)
df
# header=None 헤더가 없음을 알려준다

                0
0  C1  1  2  3  4
1  C2  5  6  7  8
2  C3  1  3  5  7

In [69]:
df = pd.read_csv('/content/text_without_column_name.txt', sep='|', 
                 names=['ID', 'A', 'B', 'C', 'D'], header=None, index_col='ID')
df
#변수 이름(column name, header) 이 없는 파일 불러올 때 이름 부여하기
#: names=['X1', 'X2', ... ], header=None

    A  B  C  D
ID
C1  1  2  3  4
C2  5  6  7  8
C3  1  3  5  7

In [ ]:
f