<a href="https://colab.research.google.com/github/chohyungrae/Python-Study-/blob/master/FinanceDataReader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

KRX 한국 거래소 전체 종목 리스트 수집 - FinanceDataReader
https://www.youtube.com/watch?v=qexaEUqvRic&list=PLaTc2c6yEwmowZCEZ6tE7_Tv8xuGlFth5&index=2

In [1]:
!pip install -U finance-datareader

Collecting finance-datareader
  Downloading https://files.pythonhosted.org/packages/83/5e/54306e72b5ff5d5ec6cc9f32cdf19602237f9bb70d64efcd527338388be3/finance_datareader-0.9.31-py3-none-any.whl
Collecting requests-file
  Downloading https://files.pythonhosted.org/packages/77/86/cdb5e8eaed90796aa83a6d9f75cfbd37af553c47a291cd47bc410ef9bdb2/requests_file-1.5.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pandas>=0.19.2 in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (1.1.5)
Requirement already satisfied, skipping upgrade: tqdm in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (4.41.1)
Requirement already satisfied, skipping upgrade: requests>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (2.23.0)
Requirement already satisfied, skipping upgrade: lxml in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (4.2.6)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.7/dist-packages (from requests-file->finance-datareader) (1.15.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (2018.9)
Requirement already satisfied, skipping upgrade: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (1.19.5)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (2020.12.5)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (2.10)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (1.24.3)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (3.0.4)
Installing collected packages: requests-file, finance-datareader
Successfully installed finance-datareader-0.9.31 requests-file-1.5.1

In [2]:
import pandas as pd

In [4]:
import FinanceDataReader as fdr
fdr. __version__

'0.9.31'

In [7]:
fdr.StockListing #끝에 ?붙이면 도움말을??을 붙이면 소스코드를 볼수있다./

In [11]:
df_krx = fdr.StockListing("KRX") #한국거래소 상장종목 존체 가져오기
df_krx

      Symbol  Market  ...                       HomePage Region
0     060310  KOSDAQ  ...           http://www.3sref.com  서울특별시
1     095570   KOSPI  ...         http://www.ajnet.co.kr  서울특별시
2     006840   KOSPI  ...  http://www.aekyunggroup.co.kr  서울특별시
3     054620  KOSDAQ  ...   http://www.apsholdings.co.kr    경기도
4     265520  KOSDAQ  ...     http://www.apsystems.co.kr    경기도
...      ...     ...  ...                            ...    ...
7296  000547   KOSPI  ...                            NaN    NaN
7297  000545   KOSPI  ...                            NaN    NaN
7298  003280   KOSPI  ...         http://www.heung-a.com  서울특별시
7299  037440  KOSDAQ  ...          http://www.heerim.com  서울특별시
7300  238490  KOSDAQ  ...          http://www.hims.co.kr  인천광역시

[7301 rows x 10 columns]

In [12]:
df_krx.shape #행과열의 크기

(7301, 10)

In [13]:
df_krx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7301 entries, 0 to 7300
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Symbol          7301 non-null   object
 1   Market          7301 non-null   object
 2   Name            7301 non-null   object
 3   Sector          2425 non-null   object
 4   Industry        2406 non-null   object
 5   ListingDate     2425 non-null   datetime64[ns]
 6   SettleMonth     2425 non-null   object
 7   Representative  2425 non-null   object
 8   HomePage        2248 non-null   object
 9   Region          2425 non-null   object
dtypes: datetime64[ns](1), object(9)
memory usage: 627.4+ KB

In [15]:
df_krx.describe() #기술통계값

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  """Entry point for launching an IPython kernel.

        Symbol Market   Name  ... Representative                   HomePage Region
count     7301   7301   7301  ...           2425                       2248   2425
unique    7301      3   7301  ...           2309                       2227     22
top     101390  KOSPI  대성에너지  ...              -  http://www.taegugas.co.kr  서울특별시
freq         1   5653      1  ...              5                          2    979
first      NaN    NaN    NaN  ...            NaN                        NaN    NaN
last       NaN    NaN    NaN  ...            NaN                        NaN    NaN

[6 rows x 10 columns]

In [16]:
df_krx.to_csv("krx.csv") #저장

In [17]:
pd.read_csv("krx.csv") #불러오기

      Unnamed: 0  Symbol  ...                       HomePage Region
0              0  060310  ...           http://www.3sref.com  서울특별시
1              1  095570  ...         http://www.ajnet.co.kr  서울특별시
2              2  006840  ...  http://www.aekyunggroup.co.kr  서울특별시
3              3  054620  ...   http://www.apsholdings.co.kr    경기도
4              4  265520  ...     http://www.apsystems.co.kr    경기도
...          ...     ...  ...                            ...    ...
7296        7296  000547  ...                            NaN    NaN
7297        7297  000545  ...                            NaN    NaN
7298        7298  003280  ...         http://www.heung-a.com  서울특별시
7299        7299  037440  ...          http://www.heerim.com  서울특별시
7300        7300  238490  ...          http://www.hims.co.kr  인천광역시

[7301 rows x 11 columns]

In [18]:
df_krx.head()

   Symbol  Market  ...                       HomePage Region
0  060310  KOSDAQ  ...           http://www.3sref.com  서울특별시
1  095570   KOSPI  ...         http://www.ajnet.co.kr  서울특별시
2  006840   KOSPI  ...  http://www.aekyunggroup.co.kr  서울특별시
3  054620  KOSDAQ  ...   http://www.apsholdings.co.kr    경기도
4  265520  KOSDAQ  ...     http://www.apsystems.co.kr    경기도

[5 rows x 10 columns]

In [19]:
df_krx.to_csv("krx.csv", index=False) #index는 빼고 저장

In [21]:
pd.read_csv("krx.csv") #다시불러오기(Unnamed가 없는 것 확인)

      Symbol  Market  ...                       HomePage Region
0     060310  KOSDAQ  ...           http://www.3sref.com  서울특별시
1     095570   KOSPI  ...         http://www.ajnet.co.kr  서울특별시
2     006840   KOSPI  ...  http://www.aekyunggroup.co.kr  서울특별시
3     054620  KOSDAQ  ...   http://www.apsholdings.co.kr    경기도
4     265520  KOSDAQ  ...     http://www.apsystems.co.kr    경기도
...      ...     ...  ...                            ...    ...
7296  000547   KOSPI  ...                            NaN    NaN
7297  000545   KOSPI  ...                            NaN    NaN
7298  003280   KOSPI  ...         http://www.heung-a.com  서울특별시
7299  037440  KOSDAQ  ...          http://www.heerim.com  서울특별시
7300  238490  KOSDAQ  ...          http://www.hims.co.kr  인천광역시

[7301 rows x 10 columns]